public class Class01 {
    public static void main(String[] args) {
        //V1 calismalarim...
        //V2 kodlari...
        //V3 calismalar...
        //V4
        //GitHub degisiklikleri..
        //Local'den sevgilerle...



    }//main
}//class
